Bitcoin_covid_study_proj:
  outputs:
    dev:
      dataset: B_C_model_bitcoin_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dags/files/bitcoin-and-covid-comparison-0919b2e95809.json
      location: US
      method: service-account
      priority: interactive
      project: bitcoin-and-covid-comparison
      threads: 1
      type: bigquery
  target: dev